### ISSUE TITLE
Laptop updated, command line to call automation doesn't now work

### ISSUE THREAD

**Issue by dconnaghanx** [mapaction/mapactionpy_arcmap#25]
It worked and then overnight I updated my laptop (unsure what as I just click 'make sense' or some such button. When I tried to run cmd call to automation with:
C:\Python27\ArcGIS10.6\python.exe -m mapactionpy_arcmap.arcmap_runner --cmf "C:\ff_GitHub\default-crash-move-folder\20YYiso3nn" --product "Country Overview with Admin 1 & 2 Boundaries" --export --orientation "portrait"

I get an error message saying 'Access is denied'

![image](https://user-images.githubusercontent.com/56038963/74591651-97d1da00-5011-11ea-9979-64d480469441.png)

**Comment by andrewphilipsmith** [comment]
Some questions for you:

What version of ArcMap and Windows do you have?

What are the version numbers of each of the components that you have now?
* For the python modules:
```
C:\Python27\ArcGIS10.6\python.exe -m pip list
```
* For the Addin see the full version number in the About box.

What actually is the error message - "Access is denied" or "This app can't run on your PC"?
* When and where does "Access is denied" appear?
* Does the error dialog shown (ie "This app can't run on your PC") appear when you run the tool at the command line or from the Addin?

Do you have any of the files open in an instance of ArcMap at the same time as trying to run the commandline tool?

**Comment by dconnaghanx** [comment]
Andy
in answer to your questions, I hope they make sense:

ArcMap: 10.6.1
Windows: 10 Pro although I don't know what 'patches' have been implemented, can you advise how I can find that out and is it important (probably yes)
Python modules: 2.7.14
MapAction toolbar: Version 4.1.7345.32745 Compiled 10/02/2020 18:11

When I type in cmd: C:\Python27\ArcGIS10.6\python.exe -m pip list I get the same error message so with my limited knowledge, seems an issue. When I look in that directory I have a python.exe (0kb) and python2.exe (27kb) so if python.exe is empty, it's defo not going to work

Screen shot in initial error shows the message "This app can't run on your PC" which appears after I type in at command prompt:
C:\Python27\ArcGIS10.6\python.exe -m mapactionpy_arcmap.arcmap_runner --cmf "C:\ff_GitHub\default-crash-move-folder\20YYiso3nn" --product "Country Overview with Admin 1 & 2 Boundaries" --export --orientation "portrait"

The error dialog shown appears when I run the tool at the command line

I have no files open in an instance of ArcMap at the same time as trying to run the command line tool, I have checked Task Manager and nothing ArcGIS, ArcMap or ArcCatalog is visible

Cheers in advance
Darren

**Comment by andrewphilipsmith** [comment]
If you have a zero- sized python.exe then there is a serious problem with your python installation. You wil need to fix this before you can determine whether or not the mapactionpy_arcmap modules are working.
